# Generated by Django 4.0.3 on 2022-04-18 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appoinment', '0006_alter_appoinment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_album', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concept_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_selection', models.IntegerField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Shoot_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Shoot_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='photoshoot.album_info')),
                ('num_of_concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='photoshoot.concept_info')),
                ('shoot_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='photoshoot.shoot_type')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shoot_Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='photoshoot.concept')),
                ('shoot_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='photoshoot.shoot_plan')),
            ],
        ),
        migrations.CreateModel(
            name='Shoot_Appoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appoinment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appoinment.appoinment')),
                ('shoot_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='photoshoot.shoot_plan')),
            ],
        ),
        migrations.CreateModel(
            name='Photo_Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.ImageField(max_length=1000, upload_to='images/')),
                ('concept_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='photoshoot.concept')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_choice', models.CharField(choices=[('EFT', 'EFT/HAVALE'), ('CASH', 'Nakit')], max_length=45)),
                ('is_paid', models.BooleanField(default=False)),
                ('shoot_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='photoshoot.shoot_plan')),
            ],
        ),
        migrations.AddField(
            model_name='concept',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='photoshoot.shoot_type'),
        ),
    ]
