# Generated by Django 4.0.3 on 2022-05-02 09:54

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('photoshoot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoot_plan',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoot_plan',
            name='payment_choice',
            field=models.CharField(choices=[('EFT', 'EFT/HAVALE'), ('CASH', 'Nakit')], default='EFT', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoot_plan',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo_concept',
            name='file_url',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=30, size=[1920, 1080], upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
