# Generated by Django 4.0.3 on 2022-05-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoshoot', '0002_shoot_plan_is_paid_shoot_plan_payment_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoot_plan',
            name='birth_date',
            field=models.DateTimeField(default='2022-03-22'),
            preserve_default=False,
        ),
    ]
