# Generated by Django 4.0.3 on 2022-05-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoshoot', '0003_shoot_plan_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoot_plan',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
