# Generated by Django 3.2.9 on 2022-01-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='offdays',
            name='date',
            field=models.DateField(),
        ),
    ]
