# Generated by Django 4.0.3 on 2022-04-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinment', '0002_auto_20220114_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offdays',
            name='time',
            field=models.CharField(choices=[('OFFMO', 'Morning'), ('OFFNO', 'Noon'), ('OFFEV', 'Evening'), ('OFFALL', 'AllDay')], max_length=30),
        ),
    ]
