# Generated by Django 4.0.3 on 2022-04-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinment', '0003_alter_offdays_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offdays',
            name='time',
            field=models.CharField(choices=[('OFFMO', 'Morning'), ('OFFNO', 'Noon'), ('OFFEV', 'Evening')], max_length=30),
        ),
    ]
