# Generated by Django 4.0.3 on 2022-04-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinment', '0004_alter_offdays_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinment',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('APR', 'Approved')], default='test', max_length=30),
            preserve_default=False,
        ),
    ]
