# Generated by Django 4.0.3 on 2022-04-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinment', '0005_appoinment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('APR', 'Approved')], default='PEN', max_length=30),
        ),
    ]
